### ISSUE TITLE
Create a seller app and Seller model

### ISSUE THREAD

**Issue by PradyumnaKrishna** [CC-BHU/marketplace#7]
Create a new seller app just like #1 and add a `Seller` model that will contain details related to seller.

Here are the attributes of `Seller`:
`name`: Name of the seller (required)
`phone`: Phone no of the seller (required)
`email`: Email of the seller (required)
`location`: Address of the seller (not required)

**Comment by uditagrawal08** [comment]
please assign this issue to me

**Comment by PradyumnaKrishna** [comment]
Sure @uditagrawal08
